### ISSUE TITLE
Broadcast UDP

### ISSUE THREAD

**Issue by deviator** [huntlabs/hunt#14]
In [example](https://github.com/huntlabs/kiss/blob/master/examples/UdpDemo/source/app.d#L65) highlights a problem: doesn't work if use 255.255.255.255 addr.
Will it be fixed?

**Comment by Heromyth** [comment]
It seems not so easy to fix it.  It needs more examples to check out what happend to it.
We will continue watching it.

**Comment by Heromyth** [comment]
Fixed in commit f671172fe3e6b19221030b7f3a68aa61e8d0b069
