### ISSUE TITLE
Port java.time package?

### ISSUE THREAD

**Issue by zoujiaqing** [huntlabs/hunt#23]
Is that necessary?
Is that possible?

java 8.x reconstracts the java.time module.
Improved ease of use.

@Heromyth @zhangyuchun

**Comment by zoujiaqing** [comment]
Features

A selection of key features:
1.     LocalDate - date without time
2.     LocalTime - time without date
3.     Instant - an instantaneous point on the time-line
4.     DateTime - full date and time with time-zone
5.     DateTimeZone - a better time-zone
6.     Duration and Period - amounts of time
7.     Interval - the time between two instants
8.     A comprehensive and flexible formatter-parser

**Comment by zoujiaqing** [comment]
@gaoxincheng this module dependence core.* (runtime) only.

**Comment by Heromyth** [comment]
See: https://github.com/huntlabs/hunt-time
