### ISSUE TITLE
Port darg to hunt.util.arg?

### ISSUE THREAD

**Issue by zoujiaqing** [huntlabs/hunt#26]
Hi @jasonwhite
I want port darg file to hunt.util.arg module.

**Comment by jasonwhite** [comment]
Hi @zoujiaqing, I appreciate you asking first instead of just going for it.

Can you give a little more detail about this? What is the motivation? Is it a copy-paste port? Would you keep the copyright? What is the plan for keeping it up to date (not that it changes very often)?

**Comment by zoujiaqing** [comment]
@jasonwhite , I want it of hunt. You can join huntlabs opensource org. You are hunt libarary contributor :)

We want hunt library to be better and no dependencies ( only use standard libraries).
