### ISSUE TITLE
咨询几个问题

### ISSUE THREAD

**Issue by huangyy** [huntlabs/hunt#52]
1. 这个lib的API文档有吗？好像文档都没有，要去看源代码。。。
2. 能否增加一个模块，就是GBK和UTF8的互转，这个功能D里面不支持。

**Comment by zoujiaqing** [comment]
1. 文档在后面会逐步补上，目前我们开发精力关注在很多重要的技术点上。
2. 编码转换方面我们看看能不能在 hunt.text 方面加入一些特性去支持，你们使用D语言主要的应用场景也可以说说看，我们后面也可以考虑在那些应用场景丰富一下，毕竟我们现在应用场景都是在服务端架构和高并发场景。
