### ISSUE TITLE
Consider breaking out concurrency library into a standalone project

### ISSUE THREAD

**Issue by dibyendumajumdar** [huntlabs/hunt#55]
Hi,

I get the impression that you have ported OpenJDK code in many places ... this has potential IP issues. Firstly you should probably retain the OpenJDK copyright - and that implies GPL plus Classpath exception. But please be aware of potential IP issues.

The concurrency libraries however can be based on Doug Lea's version which is in the public domain. I suggest breaking out the concurrency library so that it is not tainted by Oracle IP.

Regards

**Comment by zoujiaqing** [comment]
@dibyendumajumdar 
Thank you for your advice.
We will consider this design in the next version.

**Comment by Heromyth** [comment]
Fixed in version 1.6.
