### ISSUE TITLE
There may be bugs in Radix tree.

### ISSUE THREAD

**Issue by shove70** [huntlabs/hunt#56]
On MacOS, There may be bugs in Radix tree.

```
import std.stdio;

import core.stdc.stdlib;
import core.stdc.string;

import hunt.collection.Radix;

void main()
{
	byte[] data = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9 ];
	ubyte[] key = cast(ubyte[])"A key";

	void *value = malloc(data.length + 4);
	uint len = cast(uint)data.length;
	memcpy(value, &len, 4);
	memcpy(value + 4, data.ptr, data.length);

	rax *r;
	r = rax.New();
	writeln("Insert: ", r.Insert(key, value));


	void *read;
	if (!r.find(key, read))
	{
	    writeln("Not found.");
	    return;
	}

	memcpy(&len, read, 4);
	data = new byte[len];
	memcpy(data.ptr, read + 4, len);
	writeln(data);
	
	r.Remove(key);
	rax.Free(r);
}

```
Using this code to test, run it several times, and you will get different results:

```
1:
Running ./hunttest_radix
Insert: 1
Not found.
```

```
2:
Running ./hunttest_radix
Insert: 1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(Program does not exit, there is a dead cycle...)
```

```
3:
Running ./hunttest_radix
Insert: 1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Program exited with code -11
```

```
4:
Running ./hunttest_radix
Insert: 1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(Normal end as expected)
```

Radix has a problem that prevents hunt-framework from working properly.

**Comment by shove70** [comment]
Reproduction steps:

1. Write a program with session get and set functions and run it
2. Open the browser and access it, such as http://127.0.0.1:8080
3. Visit a session get or set page
4. Ctrl + C quit the program, but don't close the browser
5. Rerun the program
6. Refresh directly on previous browser windows

From this analysis, the possible reasons for the problem are: trying to get a non-existent node from the Radix tree. Because the old browser window retains an old sessionId and passes it to the server.

**Comment by shove70** [comment]
2019-06-04 16:17:38 (10EC249) [error] __lambda7 - core.exception.RangeError@../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d(1373): Range violation
----------------
??:? _d_arrayboundsp [0x10aafb6b1]
../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d:1373 uint hunt.collection.Radix.rax.find(const(ubyte[]), ref hunt.collection.Radix.raxNode*, ref hunt.collection.Radix.raxNode*, ref uint, ref uint, ref hunt.collection.Radix.raxItem[]) [0x10aaa76c3]
../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d:1359 uint hunt.collection.Radix.rax.find(const(ubyte[]), ref hunt.collection.Radix.raxNode*, ref hunt.collection.Radix.raxNode*, ref uint, ref uint, ref hunt.collection.Radix.raxItem[]) [0x10aaa7621]
../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d:1293 bool hunt.collection.Radix.rax.find(const(ubyte[]), out void*) [0x10aaa730b]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/memory.d:187 hunt.cache.nullable.Nullable!(uint).Nullable hunt.cache.memory.MemoryCache.get_inter!(uint).get_inter(hunt.collection.Radix.rax*, immutable(char)[]) [0x10a28a17e]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/memory.d:159 hunt.cache.nullable.Nullable!(immutable(char)[]).Nullable hunt.cache.memory.MemoryCache.get_inter!(immutable(char)[]).get_inter(immutable(char)[]) [0x10a289fdf]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/memory.d:25 hunt.cache.nullable.Nullable!(immutable(char)[]).Nullable hunt.cache.memory.MemoryCache.get!(immutable(char)[]).get(immutable(char)[]) [0x10a289f63]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/cache.d:12 hunt.cache.nullable.Nullable!(immutable(char)[]).Nullable hunt.cache.cache.Cache!(hunt.cache.memory.MemoryCache).Cache.get_ex!(immutable(char)[]).get_ex(immutable(char)[]) [0x10a289ef2]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/cache.d:19 immutable(char)[] hunt.cache.cache.Cache!(hunt.cache.memory.MemoryCache).Cache.get!(immutable(char)[]).get(immutable(char)[]) [0x10a289e9b]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/ucache.d-mixin-17:17 immutable(char)[] hunt.cache.ucache.UCache.get!(immutable(char)[]).get(immutable(char)[]) [0x10a289e1b]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/http/session/SessionStorage.d:44 hunt.framework.http.session.HttpSession.HttpSession hunt.framework.http.session.SessionStorage.SessionStorage.get(immutable(char)[]) [0x10a28865e]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/http/Request.d:766 @property hunt.framework.http.session.HttpSession.HttpSession hunt.framework.http.Request.Request.session(bool) [0x10a28260d]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Controller.d-mixin-166:283 hunt.framework.http.RedirectResponse.RedirectResponse app.controller.IndexController.IndexController.login() [0x10a1509cf]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Controller.d-mixin-166:228 hunt.framework.http.Response.Response app.controller.IndexController.IndexController.__mixin7.__mixin1.callActionMethod(immutable(char)[], hunt.framework.http.Request.Request) [0x10a1502b1]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Controller.d-mixin-166:283 hunt.framework.http.Response.Response hunt.framework.application.Controller.callHandler!(app.controller.IndexController.IndexController, "login").callHandler(hunt.framework.http.Request.Request) [0x10a153255]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Dispatcher.d:172 void hunt.framework.application.Dispatcher.doRequestHandle(hunt.framework.http.Response.Response function(hunt.framework.http.Request.Request)*, hunt.framework.http.Request.Request) [0x10a27c76f]
/Library/D/dmd/src/phobos/std/parallelism.d:444 void std.parallelism.Task!(hunt.framework.application.Dispatcher.doRequestHandle(hunt.framework.http.Response.Response function(hunt.framework.http.Request.Request)*, hunt.framework.http.Request.Request), hunt.framework.http.Response.Response function(hunt.framework.http.Request.Request)*, hunt.framework.http.Request.Request).Task.impl(void*) [0x10a20d560]
??:? void std.parallelism.AbstractTask.job() [0x10ab44856]
??:? void std.parallelism.TaskPool.doJob(std.parallelism.AbstractTask*) [0x10ab449db]
??:? void std.parallelism.TaskPool.executeWorkLoop() [0x10ab44b35]
??:? void std.parallelism.TaskPool.startWorkLoop() [0x10ab44ada]
??:? void core.thread.Thread.run() [0x10aafd933]
??:? thread_entryPoint [0x10aafcb04]
??:? _pthread_body [0x7fff6f46a2ea]
??:? _pthread_start [0x7fff6f46d248]
??:? thread_start [0x7fff6f46940c]
??:? 0x0 [0xffffffffffffffff] - ../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Dispatcher.d:214
core.exception.RangeError@../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d(1373): Range violation
----------------
??:? _d_arrayboundsp [0x10aafb6b1]
../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d:1373 uint hunt.collection.Radix.rax.find(const(ubyte[]), ref hunt.collection.Radix.raxNode*, ref hunt.collection.Radix.raxNode*, ref uint, ref uint, ref hunt.collection.Radix.raxItem[]) [0x10aaa76c3]
../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d:1359 uint hunt.collection.Radix.rax.find(const(ubyte[]), ref hunt.collection.Radix.raxNode*, ref hunt.collection.Radix.raxNode*, ref uint, ref uint, ref hunt.collection.Radix.raxItem[]) [0x10aaa7621]
../../../../.dub/packages/hunt-1.2.0/hunt/source/hunt/collection/Radix.d:1293 bool hunt.collection.Radix.rax.find(const(ubyte[]), out void*) [0x10aaa730b]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/memory.d:187 hunt.cache.nullable.Nullable!(uint).Nullable hunt.cache.memory.MemoryCache.get_inter!(uint).get_inter(hunt.collection.Radix.rax*, immutable(char)[]) [0x10a28a17e]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/memory.d:159 hunt.cache.nullable.Nullable!(immutable(char)[]).Nullable hunt.cache.memory.MemoryCache.get_inter!(immutable(char)[]).get_inter(immutable(char)[]) [0x10a289fdf]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/memory.d:25 hunt.cache.nullable.Nullable!(immutable(char)[]).Nullable hunt.cache.memory.MemoryCache.get!(immutable(char)[]).get(immutable(char)[]) [0x10a289f63]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/cache.d:12 hunt.cache.nullable.Nullable!(immutable(char)[]).Nullable hunt.cache.cache.Cache!(hunt.cache.memory.MemoryCache).Cache.get_ex!(immutable(char)[]).get_ex(immutable(char)[]) [0x10a289ef2]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/cache.d:19 immutable(char)[] hunt.cache.cache.Cache!(hunt.cache.memory.MemoryCache).Cache.get!(immutable(char)[]).get(immutable(char)[]) [0x10a289e9b]
../../../../.dub/packages/hunt-cache-0.4.1/hunt-cache/source/hunt/cache/ucache.d-mixin-17:17 immutable(char)[] hunt.cache.ucache.UCache.get!(immutable(char)[]).get(immutable(char)[]) [0x10a289e1b]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/http/session/SessionStorage.d:44 hunt.framework.http.session.HttpSession.HttpSession hunt.framework.http.session.SessionStorage.SessionStorage.get(immutable(char)[]) [0x10a28865e]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/http/Request.d:766 @property hunt.framework.http.session.HttpSession.HttpSession hunt.framework.http.Request.Request.session(bool) [0x10a28260d]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Controller.d-mixin-166:283 hunt.framework.http.RedirectResponse.RedirectResponse app.controller.IndexController.IndexController.login() [0x10a1509cf]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Controller.d-mixin-166:228 hunt.framework.http.Response.Response app.controller.IndexController.IndexController.__mixin7.__mixin1.callActionMethod(immutable(char)[], hunt.framework.http.Request.Request) [0x10a1502b1]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Controller.d-mixin-166:283 hunt.framework.http.Response.Response hunt.framework.application.Controller.callHandler!(app.controller.IndexController.IndexController, "login").callHandler(hunt.framework.http.Request.Request) [0x10a153255]
../../../../.dub/packages/hunt-framework-2.1.0/hunt-framework/source/hunt/framework/application/Dispatcher.d:172 void hunt.framework.application.Dispatcher.doRequestHandle(hunt.framework.http.Response.Response function(hunt.framework.http.Request.Request)*, hunt.framework.http.Request.Request) [0x10a27c76f]
/Library/D/dmd/src/phobos/std/parallelism.d:444 void std.parallelism.Task!(hunt.framework.application.Dispatcher.doRequestHandle(hunt.framework.http.Response.Response function(hunt.framework.http.Request.Request)*, hunt.framework.http.Request.Request), hunt.framework.http.Response.Response function(hunt.framework.http.Request.Request)*, hunt.framework.http.Request.Request).Task.impl(void*) [0x10a20d560]
??:? void std.parallelism.AbstractTask.job() [0x10ab44856]
??:? void std.parallelism.TaskPool.doJob(std.parallelism.AbstractTask*) [0x10ab449db]
??:? void std.parallelism.TaskPool.executeWorkLoop() [0x10ab44b35]
??:? void std.parallelism.TaskPool.startWorkLoop() [0x10ab44ada]
??:? void core.thread.Thread.run() [0x10aafd933]
??:? thread_entryPoint [0x10aafcb04]
??:? _pthread_body [0x7fff6f46a2ea]
??:? _pthread_start [0x7fff6f46d248]
??:? thread_start [0x7fff6f46940c]
??:? 0x0 [0xffffffffffffffff]

**Comment by shove70** [comment]
```
import std.stdio;

import core.stdc.stdlib;
import core.stdc.string;

import hunt.collection.Radix;

void main()
{
	byte[] data = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9 ];
	ubyte[] key = cast(ubyte[])"A key";

	void *value = malloc(data.length + 4);
	uint len = cast(uint)data.length;
	memcpy(value, &len, 4);
	memcpy(value + 4, data.ptr, data.length);

	rax *r;
	r = rax.New();
	writeln("Insert: ", r.Insert(key, value));


    void *read;
	if (!r.find(key, read))
	{
	    writeln("Not found.");
	    return;
	}

	memcpy(&len, read, 4);
	data = new byte[len];
	memcpy(data.ptr, read + 4, len);
	writeln(data);
	
	r.Remove(key);
	rax.Free(r);
}

```
Using this code to test, run it several times, and you will get different results:

```
1:
Running ./hunttest_radix
Insert: 1
Not found.
```

```
2:
Running ./hunttest_radix
Insert: 1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(Program does not exit, there is a dead cycle...)
```

```
3:
Running ./hunttest_radix
Insert: 1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Program exited with code -11
```

```
4:
Running ./hunttest_radix
Insert: 1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(Normal end as expected)
```

Radix has a problem that prevents hunt-framework from working properly.

**Comment by shove70** [comment]
On centos7:
line 1522: assert(r.numele == 0);
Sometimes you will encounter assertion errors.

On macOS:
In addition to the four cases mentioned above, there is a fifth case：
```
malloc: Incorrect checksum for freed object 0x7f92d74040b0: probably modified after being freed.
Corrupt value: 0x7f92d7403230
hunttest_radix(14390,0x1036375c0) malloc: *** set a breakpoint in malloc_error_break to debug
Program exited with code -6
```

Preliminary judgment: 
`void* n = malloc (... size)`
The structure lacks initialization. After adding `memset (n, 0, size);` or `*n.init;` after malloc, the error situation is greatly reduced, but it still exists.

In a word, Radix has a lot of problems, which affect the normal use of hunt-framework.

**Comment by shove70** [comment]
Personal suggestions:

The associative array of D language has perfectly realized the data storage based on hash key value. In order to make hunt-framework work properly as soon as possible, it is possible to modify hunt-cache project, temporarily abandon using Radix, and directly use the associative array.

I submitted a PR hunt-cache project, temporarily abandoning Radix and replacing it with an associative array when it comes.

If you decide to fix Radix, you can ignore this PR.

**Comment by zhangyuchun** [comment]
fixed a bug at . i run your example and radix's unittest in debian with 	dmd-2.086.0 (x86_64) well. what's compier?

**Comment by shove70** [comment]
`If (s. length = 0)` is a small problem, the key problem is not here.

DMD:2.086.0 (x86_64)

**Comment by shove70** [comment]
If (s. length = 0) is a small problem, the key problem is not here.

DMD: 2.086.0 (x86_64)
OS: MacOS 10.14.5

**Comment by shove70** [comment]
1. Run test2() in unittest in the radix.d file in centos7, and you can see the exception triggered by the `assert(r.numele == 0);`
DMD: 2.086.0 (x86_64)

2. Run my example and radix's unittest in MacOS with dmd-2.086.0 (x86_64). You can see these problems.

3. Note: Please add two lines to unittest:
test1();
test2();

**Comment by shove70** [comment]
https://github.com/huntlabs/hunt/pull/60
Fixed.
