### ISSUE TITLE
都不知道搞这么多版本，怎么能安装成功，尝试过几次从来都没有安装成功过

### ISSUE THREAD

**Issue by hawind** [huntlabs/hunt#71]
都不知道搞这么多版本，怎么能安装成功，尝试过几次从来都没有安装成功过

**Comment by zoujiaqing** [comment]
你想用 web 框架还是使用一个库文件？

如果使用 web 框架请参考项目 [Hunt Framework](https://github.com/huntlabs/hunt-framework)，使用方法如下：
```bash
git clone https://github.com/huntlabs/hunt-skeleton.git myproject
cd myproject
dub run -v
```

如果使用 [hunt library](https://github.com/huntlabs/hunt) 这个库就需要在你项目的 dub.json 中加入依赖：
```json
{
    "name": "your-project-name",
    "dependencies": {
        "hunt": "~>1.3.0"
    }
}
```

**Comment by zoujiaqing** [comment]
@hawind 提供一下你的编译信息，操作系统版本和编译器版本，包含完整的错误输出。

**Comment by Heromyth** [comment]
This question should be issued [here](https://github.com/huntlabs/hunt-skeleton/issues).
