### ISSUE TITLE
Provide a pkg-config file

### ISSUE THREAD

**Issue by Cogitri** [huntlabs/hunt#72]
It'd be nice if it was possible to build a dynamic lib of hunt and discover it via pkg-config

**Comment by zoujiaqing** [comment]
> It'd be nice if it was possible to build a dynamic lib of hunt and discover it via pkg-config

Thanks for your attention :)

We will use Meson to build the development library. The specific should be  in the next version ( 1.5.0 or 2.0.0) .

**Comment by Cogitri** [comment]
Oh, that'd be nice. Can I help with meson? I happen to know it pretty well :)

**Comment by zoujiaqing** [comment]
@Cogitri Wow, that's a great honor. Can you submit a PR?

**Comment by Cogitri** [comment]
Sure. I'm currently at meetingcpp, I'll try to look into it at the weekend :)

**Comment by Cogitri** [comment]
So I'm currently working on this and I have a few questions:

* How do you currently set HAVE_KQUEUE, HAVE_EPOLL and so on?

* How should meson generally handle the `version`s? I currently only handle these `['HUNT_DEBUG', 'HUNT_IO_DEBUG', 'HUNT_IO_DEBUG_MORE', 'HUNT_CONFIG_DEBUG']`
