### ISSUE TITLE
Use debug(HUNT_DEBUG_MORE) etc. instead of version(HUNT_DEBUG_MORE)

### ISSUE THREAD

**Issue by Cogitri** [huntlabs/hunt#74]
Using https://dlang.org/spec/version.html#debug seems more standard compliant.

**Comment by Heromyth** [comment]
It seems no different. The version works even in release mode, however the debug doesn't. Of course, the most of version(HUNT_DEBUG_MORE) can be replaced.

**Comment by Heromyth** [comment]
We will do this after your pull request #73 is merged.

**Comment by Heromyth** [comment]
It's done. See commit https://github.com/huntlabs/hunt/commit/4eff6b67fc1c97fcb60885f761651c53e6c9a43b

**Comment by Cogitri** [comment]
Thanks, gonna add support for this to meson in a bit.
