### ISSUE TITLE
Fix compilation with dmd 

### ISSUE THREAD

**Issue by Cogitri** [huntlabs/hunt#75]

**Comment by Heromyth** [comment]
We are waitting for two bugs in Phobos to be got fixed: 
https://issues.dlang.org/show_bug.cgi?id=20354
https://issues.dlang.org/show_bug.cgi?id=20355

The current working version of DMD is 2.088.1 and below

**Comment by Cogitri** [comment]
Ah, alrighty

**Comment by Heromyth** [comment]
Fixed in commit https://github.com/huntlabs/hunt/commit/b119472992428a02be9edd34f6678aa1cb8769c8
