### ISSUE TITLE
Add syslogging capabilities to hunt.logging

### ISSUE THREAD

**Issue by Cogitri** [huntlabs/hunt#76]
It'd be nice if I could use hunt.logging for both logging to the terminal and to syslog. IMHO it'd be nice if there were _SYSLOG variants in the LogLevel enum (e.g. `LogLevel.LOG_DEBUG_SYSLOG`) which would log all messages to syslog for you. I'll look into implementing this if you're interested

**Comment by Heromyth** [comment]
Of course, a new pull request is welcomed warmly.

**Comment by Cogitri** [comment]
FWIW I've switched to the std's std.experimental.logger which has a very nice interface via FileLogger.
